export const EXCHANGE_STATUS = {
  PENDING: 'pending',
  DECLINED: 'declined',
  ACCEPTED: 'accepted',
  SESSION_COMPLETED: 'session_completed',
  AWAITING_CONFIRMATION: 'awaiting_confirmation',
  COMPLETED: 'completed',
  ISSUE_REPORTED: 'issue_reported',
}

export const EXCHANGE_TRANSITIONS = {
  [EXCHANGE_STATUS.PENDING]: [
    EXCHANGE_STATUS.ACCEPTED,
    EXCHANGE_STATUS.DECLINED,
  ],
  [EXCHANGE_STATUS.ACCEPTED]: [EXCHANGE_STATUS.SESSION_COMPLETED],
  [EXCHANGE_STATUS.SESSION_COMPLETED]: [
    EXCHANGE_STATUS.COMPLETED,
    EXCHANGE_STATUS.ISSUE_REPORTED,
  ],
  [EXCHANGE_STATUS.AWAITING_CONFIRMATION]: [
    EXCHANGE_STATUS.COMPLETED,
    EXCHANGE_STATUS.ISSUE_REPORTED,
  ],
}
