export const EXCHANGE_STATUS = {
  PENDING: 'pending',
  DECLINED: 'declined',
  ACCEPTED: 'accepted',
  AWAITING_CONFIRMATION: 'awaiting_confirmation',
  CONFIRMED: 'confirmed',
  DISPUTED: 'disputed',
}

export const EXCHANGE_TRANSITIONS = {
  [EXCHANGE_STATUS.PENDING]: [
    EXCHANGE_STATUS.ACCEPTED,
    EXCHANGE_STATUS.DECLINED,
  ],
  [EXCHANGE_STATUS.ACCEPTED]: [EXCHANGE_STATUS.AWAITING_CONFIRMATION],
  [EXCHANGE_STATUS.AWAITING_CONFIRMATION]: [
    EXCHANGE_STATUS.CONFIRMED,
    EXCHANGE_STATUS.DISPUTED,
  ],
}
